---
title: 'Lista 9'
author: 'Allan'
date: '15/04/2021'
lang: "pt-br"
output: 
    pdf_document: 
        extra_dependencies: ['mathtools']
        latex_engine: pdflatex
---

# Questão 1

$$f_X(k)=f_Y(k)=\begin{cases}
  1, &0\le k\le1\\
  0, &c.c
\end{cases}$$

## a)

Temos que $A=\{(x,y)\in (0,1)\times(0,1): \; |x-y|\le \frac{1}{2}\}$


$$\begin{aligned}
  P\left(|X-Y|\le \frac{1}{2} \right)=&
  P\left(-\frac{1}{2}\le X-Y\le \frac{1}{2} \right)\Leftrightarrow
  \\ \Leftrightarrow& P\left(Y-\frac{1}{2}\le X\le Y+\frac{1}{2} , 0<Y <1\right)
\end{aligned}$$

Assim temos que:

$0<y<1 \;e\; \underbrace{y-1/2}_{\le 0}<x<\underbrace{y+1/2}_{\le 1}$

Assim observamos que para $1/2<y<1$, $x$ varia em $y-1/2<x<1$.

Para $0<y<1/2$, temos $0<x<y+ 1/2$.

Portanto:


$$\begin{aligned}
  P\left(|X-Y|\le \frac{1}{2} \right)=&
  \int_0^{\frac{1}{2}}\int_0^{y+\frac{1}{2}}1dxdy+\int_{\frac{1}{2}}^{1}\int_{y-\frac{1}{2}}^1 1dxdy
  \\=&
  \int_0^{\frac{1}{2}}y+\frac{1}{2}dy+\int_{\frac{1}{2}}^{1}\frac{3}{2}-ydy
  \\=&
  [\frac{y^2}{2}+\frac{y}{2}]\Big|_0^{\frac{1}{2}}+[\frac{3y}{2}-\frac{y^2}{2}]\Big|_{\frac{1}{2}}^{1}
  \\=&
  \frac{1}{8}+\frac{1}{4}+\frac{3}{2}-\frac{1}{2}-\frac{3}{4}+\frac{1}{8}
  \\=&
  \frac{1}{8}+\frac{2}{8}+\frac{12}{8}-\frac{4}{8}-\frac{6}{8}+\frac{1}{8}
  \\=&
  \frac{6}{8}=\frac{3}{4}
\end{aligned}$$

## b)

$$\begin{aligned}
  P\left(|\frac{X}{Y}-1| \le \frac{1}{2} \right)\Leftrightarrow&\\
  P\left(-\frac{1}{2} \le \frac{X}{Y}-1 \le \frac{1}{2} \right)\Leftrightarrow&\\
  P\left(1-\frac{1}{2} \le \frac{X}{Y} \le 1+\frac{1}{2} \right)\Leftrightarrow&\\
  P\left(Y(1-\frac{1}{2}) \le X \le Y(1+\frac{1}{2}), 0<Y<1 \right)
\end{aligned}$$

Assim obtemos que:
 $y(1-\frac{1}{2})\le x\le y(1+\frac{1}{2})\rightarrow \underbrace{\frac{y}{2}}_{\le 0} \le x\le \underbrace{\frac{3y}{2}}_{\le 1}$


Para $0<y<\frac{2}{3}$ temos $\frac{y}{2}<x<\frac{3y}{2}$

E para $\frac{2}{3}<y<1$ temos $\frac{y}{2}<x<1$

Portanto:


$$\begin{aligned}
P\left(|\frac{X}{Y}-1| \le \frac{1}{2} \right)=&
\int_{0}^{\frac{2}{3}}\int_{\frac{y}{2}}^{\frac{3y}{2}}1dxdy+\int_{\frac{2}{3}}^{1}\int_{\frac{y}{2}}^{1}1dxdy
\\=&  
\int_{0}^{\frac{2}{3}}ydy+\int_{\frac{2}{3}}^{1}1-\frac{y}{2}dy
\\=&  
[\frac{y^2}{2}]\Big|_{0}^{\frac{2}{3}}+[y-\frac{y^2}{4}]\Big|_{\frac{2}{3}}^{1}
\\=&  
\frac{4}{18}+1-\frac{1}{4}-[\frac{2}{3}-\frac{4}{36}]
\\=&  
\frac{8}{36}+\frac{36}{36}-\frac{9}{36}-\frac{24}{36}+\frac{4}{36}
\\=&  
\frac{15}{36}=
\frac{5}{12}
\end{aligned}$$

# Questão 2

$$f_X(k)=f_Y(k)=\begin{cases}
  e^{-\lambda k}\lambda &, k>0\\
  0 &, c.c
\end{cases}$$

$$\begin{aligned}
  P(X>2Y)=&P(X>2Y,Y>0)=P(X>2Y)P(Y>0)=
  \\=&
  \int_{0}^{\infty} \int_{2y}^{\infty}\lambda^2e^{-\lambda x}.e^{- \lambda y}dxdy
  \\=&
  \int_{0}^{\infty} \lambda^2.e^{- \lambda y}[\frac{-1}{\lambda}e^{-\lambda x}]\Big|_{2y}^{\infty}dy
  \\=&
  \int_{0}^{\infty} \lambda^2.e^{- \lambda y}\frac{1}{\lambda}e^{-\lambda 2y}dy
  \\=&
  \int_{0}^{\infty} \lambda.e^{- \lambda 3y}dy
  \\=&
  \frac{-1}{3\lambda}\lambda.[e^{- \lambda 3y}]\Big|_{0}^{\infty}
  \\=&
  \frac{1}{3}
\end{aligned}$$

# Questão 3

Seja 

$$\begin{aligned}
  f(x,y)=&ce^{(x^2-xy+4y^2)/2}
\end{aligned}$$

Temos que:

$$\begin{aligned}
  \int_{-\infty}^{\infty} \int_{-\infty}^{\infty} ce^{-(x^2-xy+4y^2)/2}dxdy=1=...&
\end{aligned}$$


# Questão 4

Desenha ai brow

# Questão 5

$$Z=X+Y$$

$$f_X(x).f_Y(y)=f_{X,Y}(x,y)$$

Temos que:

$$P(Z\le z)=P(X+Y\le z)=P(X \le z-Y, Y\in \Omega)=P(X \le z-Y)P(Y\in \Omega)$$

Logo (Convolução):

$$f_Z(z)=\int_{-\infty}^{\infty}f_X(z-y).f_Y(y)dy$$

## a)

Tem que ser $x>0$ e $y>0$

Para $z>0$

$$\begin{aligned}
  f_Z(z)=&
  \int_{0}^{z}\overbrace{f_X(z-y)f_Y(y)}^{>0\rightarrow 0<y<z}dy=
  \int_{0}^{z}\lambda_1\lambda_2.e^{-\lambda_1(z-y)}e^{-\lambda_2y}dy=
  \\=&
  \lambda_1\lambda_2e^{-\lambda_1z}\int_{0}^{z}e^{\lambda_1y}e^{-\lambda_2y}dy=
  \\=&
  \lambda_1\lambda_2e^{-\lambda_1z}\int_{0}^{z}e^{y(\lambda_1-\lambda_2)}dy=
  \\=&
  \frac{\lambda_1\lambda_2}{\lambda_1-\lambda_2}e^{-\lambda_1z}[e^{y(\lambda_1-\lambda_2)}]\Big|_{0}^{z}=
  \\=&
  \frac{\lambda_1\lambda_2}{\lambda_1-\lambda_2}e^{-\lambda_1z}[e^{z(\lambda_1-\lambda_2)}-1]=
  \\=&
  \frac{\lambda_1\lambda_2}{\lambda_1-\lambda_2}[e^{-\lambda_2z}-e^{-\lambda_1z}]=
\end{aligned}$$

## b)

Tem que ser $x>0$ e $y>0$

Para $z>0$

$$\begin{aligned}
  f_Z(z)=&
  \int_{0}^{z}\overbrace{f_X(z-y)f_Y(y)}^{>0\rightarrow 0<y<z}dy=
  \\=&
  \int_{0}^{z}\frac{\lambda^{\alpha_1}}{\Gamma(\alpha_1)}e^{-\lambda(z-y)} (z-y)^{\alpha_1-1}\frac{\lambda^{\alpha_2}}{\Gamma(\alpha_2)}e^{-\lambda y}  y^{\alpha_2-1}dy=
  \\=&
  \frac{\lambda^{\alpha_1 +\alpha_2 }}{\Gamma(\alpha_1) \Gamma(\alpha_2)}   e^{-\lambda z} \int_{0}^{z} (z-y)^{\alpha_1-1} y^{\alpha_2-1}dy=
  \\=&
  \frac{\lambda^{\alpha_1 +\alpha_2 }}{\Gamma(\alpha_1) \Gamma(\alpha_2)}   e^{-\lambda z} \int_{0}^{z}
  \sum_{k=0}^{\alpha_1-1} (-1)^kz^{\alpha_1-1-k}y^{k}y^{\alpha_2-1}dy
  \\=&
  \frac{\lambda^{\alpha_1 +\alpha_2 }}{\Gamma(\alpha_1) \Gamma(\alpha_2)}   e^{-\lambda z} \sum_{k=0}^{\alpha_1-1} (-1)^kz^{\alpha_1-1-k} \int_{0}^{z}
  y^{k+\alpha_2-1}dy
  \\=&
  \frac{\lambda^{\alpha_1 +\alpha_2 }}{\Gamma(\alpha_1) \Gamma(\alpha_2)}   e^{-\lambda z} \sum_{k=0}^{\alpha_1-1} (-1)^kz^{\alpha_1-1-k}
  [\frac{y^{k+\alpha_2}}{k+\alpha_2}]\Big|_{0}^{z}=
  \\=&
  \frac{\lambda^{\alpha_1 +\alpha_2 }}{\Gamma(\alpha_1) \Gamma(\alpha_2)}   e^{-\lambda z} \sum_{k=0}^{\alpha_1-1} (-1)^kz^{\alpha_1-1-k}
  \frac{z^{k+\alpha_2}}{k+\alpha_2}=
  \\=&
  \frac{\lambda^{\alpha_1 +\alpha_2 } }{\Gamma(\alpha_1) \Gamma(\alpha_2)}   e^{-\lambda z}  z^{\alpha_1+\alpha_2-1} \sum_{k=0}^{\alpha_1-1}
  \frac{(-1)^k}{k+\alpha_2}=...
\end{aligned}$$

\* Fazer u=x/z

## c)

Tem que ser $x\in \mathbb{R}$ e $y\in \mathbb{R}$

Para $z\in \mathbb{R}$

$$\begin{aligned}
  f_Z(z)=&
  \int_{-\infty}^{\infty}f_X(z-y)f_Y(y)dy=
  \\=&
  \int_{-\infty}^{\infty}
  \frac{e^{\frac{-(x-y-\mu_1)^2}{2\sigma_1^2}}}{\sqrt{\pi}\sigma_1}
  \frac{e^{\frac{-(y-\mu_2)^2}{2\sigma_2^2}}}{\sqrt{\pi}\sigma_2}dy=...
\end{aligned}$$

Sabendo que $EX=\mu_1$ e $VARX=EX^2-(EX)^2=\sigma_2^1$

então assumindo independência:

$$E(X+Y)= E(X)+E(Y)$$

e

$$Var(X+Y)=Var(X)+Var(Y)$$

assim $X+Y\sim N(\mu_1+\mu_2,\sigma^2_1+\sigma^2_2)$

# Questão 6

...

# Questão 7

$$X=Y\sim N(0,\sigma^2)$$

Temos que $P(R>0)=1$

onde $R=\sqrt{X^2+Y^2}$

$R=\sqrt{X^2+Y^2},\; X\le \sqrt{z^2 - Y^2},Y\in \Omega$

Temos que $A_z=\{(x,y)\in \mathbb{R}^2: \; \sqrt{x^2+y^2}\le z\}$


Para $z>0$

$$P(R\le z)=\int_{-\infty}^{z}f_R(r)dr=\int_{-\infty}^{\infty} \int_{-\infty}^{\sqrt{z^2-y^2}} f_{X,Y}(x,y)dxdy=\int \int_{A_z} f_{X,Y}(x,y)dxdy$$



ou por coordenadas polares (mudança de variável) faríamos:

$$P(R\le z)=\int_{0}^{z} \int_{0}^{2\pi} f_{X,Y}(sen^2(\theta),cos^2(\theta))r d\theta dr$$


# Questão 8

$P(X>0)=1$
$P(Y>0)=1$

$$Z=\frac{Y}{X}$$

$P(Z>0)=1$

Podemos achar:

$$F_Z(z)=P(Y\le Xz)=F_{X,Y}(\Omega,xz)$$
$$f_Z(z)=\frac{\partial}{\partial z}F_{X,Y}(\Omega,xz)$$

que no caso:

$$F_Z(z)=P(\frac{Y}{X}\le z)=P(Y\le Xz)=\int_0^{\infty}\int_0^{xz}f_{X,Y}(x,y)dydx=F_{X,Y}(\Omega,xz)$$

ou por mudança de variável:

$$\begin{cases}
  u=x \rightarrow x=u &, x>0,u>0,z>0\\
  z=\frac{x}{y} \rightarrow y=\frac{u}{z} &,y>0,u>0,z>0\\
  &, u>0 \; e\; z>0
\end{cases}$$ e

$J=\begin{bmatrix}
  1 & 0\\
  \frac{1}{y} & \frac{-x}{y^2}
\end{bmatrix}= \frac{-x}{y^2}$

assim:

$$f_{U,Z}(u,z)=\frac{y^2}{x}f_{X,Y}(u,\frac{x}{y})$$

e $f_Z(z)=\int_0^{\infty}f_{U,Z}(u,z)du$

# Questão 9

Seja $X\sim Gamma(\alpha_1,\lambda)$ e $Y\sim Gamma(\alpha_2,\lambda)$

onde $P(X>0)=1=P(Y>0)$

Temos que $F_{X,Y}(x,y)=F_{X}(x)F_{Y}(y)$

e $Z=\frac{X}{X+Y}$

Então

$$\begin{aligned}
  F_Z(Z\le z)&=
  P(\frac{X}{X+Y}\le z)=P(X\le (X+Y)z)=P(X\le Xz+Yz)=
  \\=&
  P(X-Xz\le Yz)=P(X(1-z)\le Yz)=
  \\=&
  P(X\le \frac{Yz}{(1-z)},Y\in \Omega)
\end{aligned}$$

Assim

$$\begin{aligned}
  F_Z(Z\le z)=&
  \int_0^{\infty} \int_{0}^{\frac{yz}{(1-z)}}F_{X,Y}(x,y)dxdy
\end{aligned}$$

Ou por mudança de variáveis:

$Z=\frac{X}{X+Y}=\frac{1}{1+\frac{Y}{X}}=\frac{1}{1+W}$ em que $W=\frac{X}{Y}$

Assim

$$F_Z(z)=P(\frac{1}{1+W}\le z)=P(\frac{1}{z}\le W+1)=P(W \ge \frac{1}{z} -1)= 1-P(W\le \frac{1}{z}-1)$$

e sendo assim para $z>0$

$$f_z(z)=f_W(\frac{1}{z}-1).\frac{1}{z^2}$$

onde $\frac{1}{z}-1>0 \rightarrow 0<z<1$

no qual $F_W(w)=P(W\le w)=P(\frac{X}{Y}\le w)=P(X\le wY,Y\in \Omega)=F_{X,Y}(wy,\Omega)$

Fazendo uma mudança de variável de $u=\frac{x}{y}$ com $du=\frac{1}{y}dx$

assim $$f_{W}(w)=\int_0^{\infty}y.f_{X,Y}(yu,y)dy$$

# Questão 10

## a)


$$Z=\rho U+\sqrt{1-\rho^2}V $$

Para $U=V\sim N(0,1)$

Seja: 

$\rho U \sim N(0,\rho^2 )$
$\sqrt{1-\rho^2}V \sim N(0,1-\rho^2 )$

Assim

$EZ=E(\rho U) + E(\sqrt{1-\rho^2}V)=0+0=0$
$VarZ=Var(\rho U) + Var(\sqrt{1-\rho^2}V)=\rho^2 +1-\rho^2=1$

$Z\sim N(0,1)$

## b)

para $\begin{cases}
  x=u &\rightarrow u= x\\
  z=\rho u+\sqrt{1-\rho^2}v & \rightarrow v= \frac{-\rho}{\sqrt{1-\rho^2}}x +\frac{1}{\sqrt{1-\rho^2}}z
\end{cases}$

$J=\sqrt{1-\rho^2}$

$$f_{U,Z}(u,z)=f_{X,Z}(x,z)=\frac{1}{|J|}f_{U,V}(x, \frac{-\rho}{\sqrt{1-\rho^2}}x +\frac{1}{\sqrt{1-\rho^2}})$$


## c)

para $\begin{cases}
  x=\mu_1 +\sigma_1u \rightarrow u= \frac{x-\mu_1}{\sigma_1}&,x\in\mathbb{R},u\in\mathbb{R} \\
  y=\mu_2 +\sigma_2z  \rightarrow z= \frac{y-\mu_2}{\sigma_2}&, y\in\mathbb{R},z\in\mathbb{R}
\end{cases}$

$J=det\begin{bmatrix}
  \sigma_1 & 0\\
  0 & \sigma_2
\end{bmatrix}=\sigma_1.\sigma_2$


$$f_{X,Y}(x,y)=\frac{1}{\sigma_1\sigma_2 }f_{U,Z}(\frac{x-\mu_1}{\sigma_1}, \frac{y-\mu_2}{\sigma_2})$$

# Questão 11

$$f_R(r)=\begin{cases}
  \sigma^{-2}re^{-r^2/2\sigma^2} &, r\ge 0\\
  0 &, c.c
\end{cases}$$

e

$$f_\Theta(\Theta)=\begin{cases}
  \frac{1}{2\pi} &, -\pi<\Theta<\pi\\
  0&,x.x
\end{cases}$$


Para 

$$\begin{cases}
  x=rcos\theta  \rightarrow r=\sqrt{x^2+y^2}&, r>0, x\in \mathbb{R}\\
  y=rsen\theta \rightarrow  \theta= arcsen(\frac{y}{x})&, \frac{-\pi}{2}<\theta<\frac{\pi}{2}, y\in \mathbb{R}\\
\end{cases}$$

$$J=r$$
Assim

$$f_{X,Y}(x,y)=\frac{1}{r}f_{R,\Theta}(\sqrt{x^2+y^2}, arcsen(\frac{y}{x}))=...$$
